name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-cicd-project:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-cicd-project:latest

          - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-cicd-project:latest

      - name: Test SSH connection
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$EC2_SSH_KEY" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
          ssh -v -i ~/.ssh/github-actions "$EC2_USERNAME@$EC2_HOST" "echo SSH_CONNECTION_SUCCESSFUL"
